### ISSUE TITLE
Error on running ThunderSTORM

### ISSUE THREAD

**Issue by zitmen** [zitmen/thunderstorm#24]
```
What steps will reproduce the problem?
1. I just went to use ThunderSTORM for the first time and received the error log below
on clicking preview in run analysis
2.
3.

What is the expected output? What do you see instead?

(Fiji Is Just) ImageJ 2.0.0-rc-29/1.49q; Java 1.6.0_65 [64-bit]; Mac OS X 10.10.3;
139MB of 10231MB (1%)
 
org.apache.commons.math3.exception.ConvergenceException: illegal state: unable to perform
Q.R decomposition on the 49x11 jacobian matrix
	at org.apache.commons.math3.optim.nonlinear.vector.jacobian.LevenbergMarquardtOptimizer.qrDecomposition(LevenbergMarquardtOptimizer.java:888)
	at org.apache.commons.math3.optim.nonlinear.vector.jacobian.LevenbergMarquardtOptimizer.doOptimize(LevenbergMarquardtOptimizer.java:335)
	at org.apache.commons.math3.optim.nonlinear.vector.jacobian.LevenbergMarquardtOptimizer.doOptimize(LevenbergMarquardtOptimizer.java:116)
	at org.apache.commons.math3.optim.BaseOptimizer.optimize(BaseOptimizer.java:153)
	at org.apache.commons.math3.optim.BaseMultivariateOptimizer.optimize(BaseMultivariateOptimizer.java:65)
	at org.apache.commons.math3.optim.nonlinear.vector.MultivariateVectorOptimizer.optimize(MultivariateVectorOptimizer.java:88)
	at org.apache.commons.math3.optim.nonlinear.vector.JacobianMultivariateVectorOptimizer.optimize(JacobianMultivariateVectorOptimizer.java:87)
	at org.apache.commons.math3.optim.nonlinear.vector.jacobian.AbstractLeastSquaresOptimizer.optimize(AbstractLeastSquaresOptimizer.java:201)
	at cz.cuni.lf1.lge.ThunderSTORM.estimators.LSQFitter.fit(LSQFitter.java:59)
	at cz.cuni.lf1.lge.ThunderSTORM.estimators.MultipleLocationsImageFitting.run(MultipleLocationsImageFitting.java:83)
	at cz.cuni.lf1.lge.ThunderSTORM.estimators.MultipleLocationsImageFitting.estimateParameters(MultipleLocationsImageFitting.java:134)
	at cz.cuni.lf1.lge.ThunderSTORM.UI.AnalysisOptionsDialog$2.run(AnalysisOptionsDialog.java:288)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)


What version of the product are you using? On what operating system?

I am using version 1.3 in FIJI on Mac OS X 10.10.3

Please provide any additional information below.

```

Original issue reported on code.google.com by `colin.rickman` on 2015-04-21 15:39:59

**Comment by zitmen** [comment]
fixed in commit 9205895
