### ISSUE TITLE
jar error

### ISSUE THREAD

**Issue by easch** [zitmen/thunderstorm#26]
Mac OSX 10.10.4;  ImageJ 2.0.0-rc-32/1.49v;  Thunderstorm 1.3 (2014-11-8)

Click on "About ThunderSTORM" produces output below.  Subsequent attempt to "Merge" produces java.lang.NullPointerException error

# pageProperties #
stream : jar:file:/Users/ea/Desktop/Fiji.app/plugins/Thunder_STORM.jar!/resources/help/about.html
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/ea/Desktop/Fiji.app/jars/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/ea/Desktop/Fiji.app/plugins/Thunder_STORM.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Failed to auto configure default logger context
Reported exception:
ch.qos.logback.core.joran.spi.JoranException: Parser configuration error occurred
	at ch.qos.logback.core.joran.event.SaxEventRecorder.buildSaxParser(SaxEventRecorder.java:88)
	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SaxEventRecorder.java:59)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:134)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:148)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at org.fit.cssbox.css.DOMAnalyzer.<clinit>(DOMAnalyzer.java:49)
	at org.fit.cssbox.swingbox.util.DefaultAnalyzer.analyze(DefaultAnalyzer.java:52)
	at org.fit.cssbox.swingbox.util.ContentReader.read(ContentReader.java:112)
	at org.fit.cssbox.swingbox.SwingBoxEditorKit.readImpl(SwingBoxEditorKit.java:402)
	at org.fit.cssbox.swingbox.SwingBoxEditorKit.read(SwingBoxEditorKit.java:234)
	at org.fit.cssbox.swingbox.BrowserPane.read(BrowserPane.java:795)
	at org.fit.cssbox.swingbox.BrowserPane.loadPage(BrowserPane.java:556)
	at org.fit.cssbox.swingbox.BrowserPane.setPage(BrowserPane.java:499)
	at cz.cuni.lf1.lge.ThunderSTORM.AboutPlugIn.run(AboutPlugIn.java:62)
	at ij.IJ.runUserPlugIn(IJ.java:199)
	at ij.IJ.runPlugIn(IJ.java:163)
	at ij.Executer.runCommand(Executer.java:132)
	at ij.Executer.run(Executer.java:65)
	at java.lang.Thread.run(Thread.java:695)
Caused by: java.lang.ClassCastException: org.apache.xerces.jaxp.SAXParserFactoryImpl cannot be cast to javax.xml.parsers.SAXParserFactory
	at javax.xml.parsers.SAXParserFactory.newInstance(Unknown Source)
	at ch.qos.logback.core.joran.event.SaxEventRecorder.buildSaxParser(SaxEventRecorder.java:81)
	... 27 more
12:25:01,893 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
12:25:01,894 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
12:25:01,894 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/Users/ea/Desktop/Fiji.app/jars/scijava-config-2.0.0.jar!/logback.xml]
12:25:01,895 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
12:25:01,895 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/Users/ea/Desktop/Fiji.app/plugins/Thunder_STORM.jar!/logback.xml]
12:25:01,895 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/Users/ea/Desktop/Fiji.app/jars/scijava-config-2.0.0.jar!/logback.xml]
12:25:01,909 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@70d18a80 - URL [jar:file:/Users/ea/Desktop/Fiji.app/jars/scijava-config-2.0.0.jar!/logback.xml] is not of type file
12:25:01,916 |-ERROR in ch.qos.logback.core.joran.event.SaxEventRecorder@4cdc135d - Parser configuration error occurred java.lang.ClassCastException: org.apache.xerces.jaxp.SAXParserFactoryImpl cannot be cast to javax.xml.parsers.SAXParserFactory
	at java.lang.ClassCastException: org.apache.xerces.jaxp.SAXParserFactoryImpl cannot be cast to javax.xml.parsers.SAXParserFactory
	at 	at javax.xml.parsers.SAXParserFactory.newInstance(Unknown Source)
	at 	at ch.qos.logback.core.joran.event.SaxEventRecorder.buildSaxParser(SaxEventRecorder.java:81)
	at 	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SaxEventRecorder.java:59)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:134)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:148)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at 	at org.fit.cssbox.css.DOMAnalyzer.<clinit>(DOMAnalyzer.java:49)
	at 	at org.fit.cssbox.swingbox.util.DefaultAnalyzer.analyze(DefaultAnalyzer.java:52)
	at 	at org.fit.cssbox.swingbox.util.ContentReader.read(ContentReader.java:112)
	at 	at org.fit.cssbox.swingbox.SwingBoxEditorKit.readImpl(SwingBoxEditorKit.java:402)
	at 	at org.fit.cssbox.swingbox.SwingBoxEditorKit.read(SwingBoxEditorKit.java:234)
	at 	at org.fit.cssbox.swingbox.BrowserPane.read(BrowserPane.java:795)
	at 	at org.fit.cssbox.swingbox.BrowserPane.loadPage(BrowserPane.java:556)
	at 	at org.fit.cssbox.swingbox.BrowserPane.setPage(BrowserPane.java:499)
	at 	at cz.cuni.lf1.lge.ThunderSTORM.AboutPlugIn.run(AboutPlugIn.java:62)
	at 	at ij.IJ.runUserPlugIn(IJ.java:199)
	at 	at ij.IJ.runPlugIn(IJ.java:163)
	at 	at ij.Executer.runCommand(Executer.java:132)
	at 	at ij.Executer.run(Executer.java:65)
	at 	at java.lang.Thread.run(Thread.java:695)

SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

**Comment by zitmen** [comment]
Hi,

I was not able to replicate youe problem with the About dialog. This might be caused by some incompatibility with another plugin. As for the merging, I replicated this. This is probably an old issue, which has been already resolved, because it didn't happen after I updated to the latest daily build.
Please be sure to update to the latest daily version before reporting bugs. The dev branch is usually stable and contains fixes of reported bugs.

Best,
Martin
